### ISSUE TITLE
Support for dotnet core 2.0

### ISSUE THREAD

**Issue by AbrahamAlcaina** [fsprojects/TickSpec#8]
Do you have any plans to add support for dotnet core 2.0?
Notw it fails because It can't load the features by reflection.

**Comment by mchaloupka** [comment]
The .NET core does not support all the methods needed for code emitting. However, I guess that it should be possible to create a lightweight version for netstandard (without code emit) and full version for net45.

**Comment by tylerhartwig** [comment]
Are there any plans to proceed with dotnet core support? how significant or involved is the effort for the lightweight version (if I wanted to contribute)?

**Comment by michalkovy** [comment]
It feels relatively simple to do a .NET Standard version of TickSpec if you exclude support for debugging feature files. I have done a proof of concept some time ago in this branch https://github.com/michalkovy/tickspec/commits/feature/DotNetCore

The reason debugging feature files is harder to solve is because I haven't found at the time replacement for DefineDocument
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.modulebuilder.definedocument?view=netframework-4.7.2
and MarkSequencePoint
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.marksequencepoint?view=netframework-4.7.2

My feeling is that even though debugging feature files is nice feature there are good ways how to work differently, so it makes great sense to create .NET Standard version even without the feature.

**Comment by tylerhartwig** [comment]
With this closed, will a nuget be published in the near future?

**Comment by michalkovy** [comment]
@bartelink I think we currently don't have any known defect - so, like suggested, can you please publish a nuget package? I would consider to make it a preview first. Thanks

**Comment by tylerhartwig** [comment]
@bartelink thanks, I have a setup that works locally for the time being. I'm using this on a side project, so it's not super urgent for me to get it all in CI yet. Glad to see this come to standard though, it's a really awesome framework.
